### ISSUE TITLE
Pause view

### ISSUE THREAD

**Issue by danstsx** [Parakoos/sgt-cp#7]
Just a reminder to remove the static part of the pause animation since we dont need it anymore.

**Comment by Parakoos** [comment]
Have you tried reducing the pause time to 0? Or near 0? How does that look? 

I was also thinking of having particles of different speed and beightnesses flowing into or out of the paused player's light bar. What do you think of that idea?

**Comment by danstsx** [comment]
Yeah, i tried this:
TABLE_PAUSE_INACTIVE_DURATION = "0"
but it just blinks.

Now, thats a cool idea, i really wanna see how it looks irl. 
My vote is on the Particles flowing out of the paused players light bar .

**Comment by Parakoos** [comment]
I made the next version. The settings for this new pause animation should be something like:

```toml
# How fast does the sparks move?
TABLE_PAUSE_SPEED_PPS_MIN = "1"
TABLE_PAUSE_SPEED_PPS_MAX = "5"
TABLE_PAUSE_SPEED_PPS_DISTRIBUTION = "CubicEaseOutIn"
TABLE_PAUSE_LOCATION_EASE = "LinearInOut"

# How far do the pixels move? 0 to 0.5 (0.5 being all the way around the table)
TABLE_PAUSE_DISTANCE_MIN = "0.2"
TABLE_PAUSE_DISTANCE_MAX = "0.5"
TABLE_PAUSE_DISTANCE_DISTRIBUTION = "CubicEaseOutIn"

# How bright are the pixels, and how fast do they fade out towards the end?
TABLE_PAUSE_BRIGHTNESS_MIN = "0.01"
TABLE_PAUSE_BRIGHTNESS_MAX = "0.4"
TABLE_PAUSE_BRIGHTNESS_DISTRIBUTION = "CubicEaseOutIn"
TABLE_PAUSE_FADE_OUT_EASE = "QuarticEaseIn"

# How frequent to we potentially spawn a new spark?
TABLE_PAUSE_SPAWN_PAUSE_SEC = "0.2"
# How probable is it that we spawn a new spark?
TABLE_PAUSE_SPAWN_PROBABILITY = "0.5"
```

I imagine you will want to change at least the speed in PPS to better match your table. The rest might be OK.
